### PR TITLE
Prepare release v47

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by rg3** [comment]
Similar to the master branch, replace http with https in the program webpage URL in the following files: docinfo.html, tutorial.html and faq.html. Sorry again for not noticing before.

**Comment by rg3** [comment]
It would also be interesting to change "a link to the Frequently Asked Questions document" with "a Frequently Asked Questions section" in the man page. Explanation: the FAQ, tutorial and main page were separated previously. We now redirect everything to the main page, but this wording was left behind.

**Comment by aclemons** [comment]
Ok, those updates should be in the HTML files now.

**Comment by rg3** [comment]
Er, the man page wording is actually in the master branch instead of this one. :-\

**Comment by aclemons** [comment]
I've pushed that change to the PR for the master branch now too.

**Comment by rg3** [comment]
All perfect now. Just mail me the package and I'll upload it and push the changes. Thanks again.

**Pull request merged**
