### PR TITLE
Add support for slackwarearm

### PR DESCRIPTION
**Pull request by aclemons**
Adjusts a couple of regex values to also match `slackwarearm` as well.

### CODE REVIEW

**Comment by rg3** [comment]
Big question: have you actually tried to use slackroll on Slackware ARM? I ask because there may be other things that needs adjustments. For example, the primary mirror is:

http://ftp.slackware.com/pub/slackware/

Where package signatures are downloaded from, and there are not ARM Slackware directories there. Also, which bootloader does Slackware ARM use? Do slackroll_bootloader_config_files make sense for that?

**Comment by aclemons** [comment]
> Big question: have you actually tried to use slackroll on Slackware ARM?

Of course. I wouldn't submit a PR for something I haven't tested.

I always set a primary mirror with `slackroll set-primary-mirror`, but you are correct. The default primary for arm would have to be different.

> Also, which bootloader does Slackware ARM use? Do slackroll_bootloader_config_files make sense for that?

u-boot generally. That list probably does not make sense in the arm world. The installation for each supported device is slightly different, but you don't really need to update configs after upgrading the kernel. The list should probably just be empty on arm.

The kernel package for a particular device includes the initrd.

**Comment by aclemons** [comment]
I've amended this commit to use a different default for the primary mirror based on the arch. Since we don't actually have the arch anywhere explicit, I am basing it off the mirror which is set as done elsewhere, which seems reasonable. This works fine on slackare(64). I'll test it on arm later when I have access to my slackwarearm instance.

**Comment by aclemons** [comment]
Just testing on arm now. Looks good here too.

**Comment by rg3** [comment]
I don't know if you received the review comments but today I did the small changes myself and updated the list of authors. Thanks.

**Comment by rg3** [comment]
I'm a newbie when it comes to GitHub's web interface. I believe I opened  the review and wrote some comments but never actually submitted it.

**Comment by aclemons** [comment]
Nice. Looks good to me.

**Pull request closed without merging**
